[build-system]
requires = ["scikit-build-core", "setuptools", "wheel"]
build-backend = "scikit_build_core.build"

[project]
name = "firzah"
version = "0.0.1"
authors = [
  { name="firzah", email="-" }
]
description = "Package firzah yang otomatis mengompilasi user_agent.cpp"
readme = "README.md"
license = { text = "MIT" }
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent"
]

[tool.scikit-build]
wheel.packages = ["firzah"]

